name: Go Build and Release

on:
  release:
    types: [created]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.23'

    - name: Build binaries
      run: |
        chmod +x build.sh
        ./build.sh

    - name: Upload Darwin AMD64 binary
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ github.event.release.upload_url }}
        asset_path: ./semaphore-mtb-setup-darwin_amd64
        asset_name: semaphore-mtb-setup-darwin_amd64
        asset_content_type: application/octet-stream

    - name: Upload Darwin ARM64 binary
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ github.event.release.upload_url }}
        asset_path: ./semaphore-mtb-setup-darwin_arm64
        asset_name: semaphore-mtb-setup-darwin_arm64
        asset_content_type: application/octet-stream

    - name: Upload Linux 386 binary
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ github.event.release.upload_url }}
        asset_path: ./semaphore-mtb-setup-linux_386
        asset_name: semaphore-mtb-setup-linux_386
        asset_content_type: application/octet-stream

    - name: Upload Linux ARM binary
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ github.event.release.upload_url }}
        asset_path: ./semaphore-mtb-setup-linux_arm
        asset_name: semaphore-mtb-setup-linux_arm
        asset_content_type: application/octet-stream

    - name: Upload Linux ARM64 binary
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ github.event.release.upload_url }}
        asset_path: ./semaphore-mtb-setup-linux_arm64
        asset_name: semaphore-mtb-setup-linux_arm64
        asset_content_type: application/octet-stream

    - name: Upload Linux AMD64 binary
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ github.event.release.upload_url }}
        asset_path: ./semaphore-mtb-setup-linux_amd64
        asset_name: semaphore-mtb-setup-linux_amd64
        asset_content_type: application/octet-stream

